#ifndef BINDINGS_H
#define BINDINGS_H

/* This file is auto generated. DO NOT MODIFY MANUALLY! */

/*-----------------------------*/
/* sounds\dialog01_jcl */
/*-----------------------------*/
#define PRAGMA_BIND "dlg01_jcl_01.ogg"
#define PRAGMA_BIND "dlg01_jcl_03.ogg"
#define PRAGMA_BIND "dlg01_jcl_05b.ogg"
#define PRAGMA_BIND "dlg01_jcl_06.ogg"
#define PRAGMA_BIND "dlg01_jcl_08.ogg"
#define PRAGMA_BIND "dlg01_jcl_10a.ogg"
#define PRAGMA_BIND "dlg01_jcl_10b.ogg"
#define PRAGMA_BIND "dlg01_jcl_10c.ogg"
#define PRAGMA_BIND "dlg01_jcl_11.ogg"
#define PRAGMA_BIND "dlg01_jcl_13.ogg"
#define PRAGMA_BIND "dlg01_jcl_15.ogg"
#define PRAGMA_BIND "dlg01_jcl_17.ogg"
#define PRAGMA_BIND "dlg01_jcl_19.ogg"
#define PRAGMA_BIND "dlg01_jcl_21.ogg"
#define PRAGMA_BIND "dlg01_jcl_23.ogg"
#define PRAGMA_BIND "dlg01_jcl_25.ogg"
#define PRAGMA_BIND "dlg01_jcl_27.ogg"
#define PRAGMA_BIND "dlg01_jcl_29.ogg"
#define PRAGMA_BIND "dlg01_jcl_31.ogg"
#define PRAGMA_BIND "dlg01_jcl_33.ogg"
#define PRAGMA_BIND "dlg01_jcl_35.ogg"
#define PRAGMA_BIND "dlg01_jcl_37.ogg"
#define PRAGMA_BIND "dlg01_jcl_39.ogg"
#define PRAGMA_BIND "dlg01_morbius_00.ogg"
#define PRAGMA_BIND "dlg01_morbius_02.ogg"
#define PRAGMA_BIND "dlg01_morbius_04a.ogg"
#define PRAGMA_BIND "dlg01_morbius_04b.ogg"
#define PRAGMA_BIND "dlg01_morbius_07.ogg"
#define PRAGMA_BIND "dlg01_morbius_09a.ogg"
#define PRAGMA_BIND "dlg01_morbius_09b.ogg"
#define PRAGMA_BIND "dlg01_morbius_09c.ogg"
#define PRAGMA_BIND "dlg01_morbius_12.ogg"
#define PRAGMA_BIND "dlg01_morbius_14.ogg"
#define PRAGMA_BIND "dlg01_morbius_16.ogg"
#define PRAGMA_BIND "dlg01_morbius_18.ogg"
#define PRAGMA_BIND "dlg01_morbius_20.ogg"
#define PRAGMA_BIND "dlg01_morbius_22.ogg"
#define PRAGMA_BIND "dlg01_morbius_24.ogg"
#define PRAGMA_BIND "dlg01_morbius_26.ogg"
#define PRAGMA_BIND "dlg01_morbius_28.ogg"
#define PRAGMA_BIND "dlg01_morbius_30.ogg"
#define PRAGMA_BIND "dlg01_morbius_32.ogg"
#define PRAGMA_BIND "dlg01_morbius_34.ogg"
#define PRAGMA_BIND "dlg01_morbius_36.ogg"
#define PRAGMA_BIND "dlg01_morbius_38.ogg"
#define PRAGMA_BIND "monolog_morbius.ogg"

/*-----------------------------*/
/* sounds\dialog05_cbabe */
/*-----------------------------*/
#define PRAGMA_BIND "dlg05_cbabe_01.ogg"
#define PRAGMA_BIND "dlg05_cbabe_03.ogg"
#define PRAGMA_BIND "dlg05_cbabe_05.ogg"
#define PRAGMA_BIND "dlg05_cbabe_07.ogg"
#define PRAGMA_BIND "dlg05_cbabe_09.ogg"
#define PRAGMA_BIND "dlg05_cbabe_11.ogg"
#define PRAGMA_BIND "dlg05_cbabe_13.ogg"
#define PRAGMA_BIND "dlg05_cbabe_15.ogg"
#define PRAGMA_BIND "dlg05_cbabe_17.ogg"

/*-----------------------------*/
/* sounds\dialog02_fritz */
/*-----------------------------*/
#define PRAGMA_BIND "dlg02_fritz_00.ogg"
#define PRAGMA_BIND "dlg02_fritz_03.ogg"
#define PRAGMA_BIND "dlg02_fritz_05a.ogg"
#define PRAGMA_BIND "dlg02_fritz_05b.ogg"
#define PRAGMA_BIND "dlg02_fritz_06.ogg"
#define PRAGMA_BIND "dlg02_fritz_08.ogg"
#define PRAGMA_BIND "dlg02_fritz_10.ogg"
#define PRAGMA_BIND "dlg02_fritz_12.ogg"
#define PRAGMA_BIND "dlg02_fritz_14.ogg"
#define PRAGMA_BIND "dlg02_fritz_16.ogg"
#define PRAGMA_BIND "dlg02_fritz_18.ogg"
#define PRAGMA_BIND "dlg02_fritz_20.ogg"
#define PRAGMA_BIND "dlg02_fritz_22.ogg"
#define PRAGMA_BIND "dlg02_morbius_01.ogg"
#define PRAGMA_BIND "dlg02_morbius_02.ogg"
#define PRAGMA_BIND "dlg02_morbius_04a.ogg"
#define PRAGMA_BIND "dlg02_morbius_04b.ogg"
#define PRAGMA_BIND "dlg02_morbius_07.ogg"
#define PRAGMA_BIND "dlg02_morbius_09.ogg"
#define PRAGMA_BIND "dlg02_morbius_11.ogg"
#define PRAGMA_BIND "dlg02_morbius_13.ogg"
#define PRAGMA_BIND "dlg02_morbius_15.ogg"
#define PRAGMA_BIND "dlg02_morbius_17.ogg"
#define PRAGMA_BIND "dlg02_morbius_19.ogg"
#define PRAGMA_BIND "dlg02_morbius_21.ogg"

/*-----------------------------*/
/* sounds\dialog04_griechin */
/*-----------------------------*/
#define PRAGMA_BIND "dlg04_greek_01.ogg"
#define PRAGMA_BIND "dlg04_greek_03.ogg"
#define PRAGMA_BIND "dlg04_greek_05.ogg"
#define PRAGMA_BIND "dlg04_greek_07.ogg"
#define PRAGMA_BIND "dlg04_greek_09.ogg"
#define PRAGMA_BIND "dlg04_greek_11.ogg"
#define PRAGMA_BIND "dlg04_greek_14.ogg"
#define PRAGMA_BIND "dlg04_greek_16.ogg"
#define PRAGMA_BIND "dlg04_greek_18.ogg"
#define PRAGMA_BIND "dlg04_greek_20.ogg"
#define PRAGMA_BIND "dlg04_greek_22.ogg"
#define PRAGMA_BIND "dlg04_greek_24.ogg"
#define PRAGMA_BIND "dlg04_greek_26.ogg"
#define PRAGMA_BIND "dlg04_greek_28.ogg"
#define PRAGMA_BIND "dlg04_greek_30.ogg"
#define PRAGMA_BIND "dlg04_greek_32.ogg"
#define PRAGMA_BIND "dlg04_greek_34.ogg"
#define PRAGMA_BIND "dlg04_morbius_00.ogg"
#define PRAGMA_BIND "dlg04_morbius_02.ogg"
#define PRAGMA_BIND "dlg04_morbius_04.ogg"
#define PRAGMA_BIND "dlg04_morbius_06.ogg"
#define PRAGMA_BIND "dlg04_morbius_08.ogg"
#define PRAGMA_BIND "dlg04_morbius_10.ogg"
#define PRAGMA_BIND "dlg04_morbius_12.ogg"
#define PRAGMA_BIND "dlg04_morbius_13.ogg"
#define PRAGMA_BIND "dlg04_morbius_15.ogg"
#define PRAGMA_BIND "dlg04_morbius_17.ogg"
#define PRAGMA_BIND "dlg04_morbius_19.ogg"
#define PRAGMA_BIND "dlg04_morbius_21.ogg"
#define PRAGMA_BIND "dlg04_morbius_23.ogg"
#define PRAGMA_BIND "dlg04_morbius_25.ogg"
#define PRAGMA_BIND "dlg04_morbius_27.ogg"
#define PRAGMA_BIND "dlg04_morbius_29.ogg"
#define PRAGMA_BIND "dlg04_morbius_31.ogg"
#define PRAGMA_BIND "dlg04_morbius_33.ogg"

/*-----------------------------*/
/* sounds\dialog03_galep */
/*-----------------------------*/
#define PRAGMA_BIND "dlg03_galep_00.ogg"
#define PRAGMA_BIND "dlg03_galep_02.ogg"
#define PRAGMA_BIND "dlg03_galep_04.ogg"
#define PRAGMA_BIND "dlg03_galep_06.ogg"
#define PRAGMA_BIND "dlg03_galep_08.ogg"
#define PRAGMA_BIND "dlg03_galep_10.ogg"
#define PRAGMA_BIND "dlg03_galep_12.ogg"
#define PRAGMA_BIND "dlg03_galep_14.ogg"
#define PRAGMA_BIND "dlg03_galep_16.ogg"
#define PRAGMA_BIND "dlg03_galep_18.ogg"
#define PRAGMA_BIND "dlg03_galep_20.ogg"
#define PRAGMA_BIND "dlg03_galep_22.ogg"
#define PRAGMA_BIND "dlg03_galep_24.ogg"
#define PRAGMA_BIND "dlg03_morbius_01.ogg"
#define PRAGMA_BIND "dlg03_morbius_03.ogg"
#define PRAGMA_BIND "dlg03_morbius_05.ogg"
#define PRAGMA_BIND "dlg03_morbius_07.ogg"
#define PRAGMA_BIND "dlg03_morbius_09.ogg"
#define PRAGMA_BIND "dlg03_morbius_11.ogg"
#define PRAGMA_BIND "dlg03_morbius_13.ogg"
#define PRAGMA_BIND "dlg03_morbius_15.ogg"
#define PRAGMA_BIND "dlg03_morbius_17.ogg"
#define PRAGMA_BIND "dlg03_morbius_19.ogg"
#define PRAGMA_BIND "dlg03_morbius_21.ogg"
#define PRAGMA_BIND "dlg03_morbius_23.ogg"

/*-----------------------------*/
/* sounds\items */
/*-----------------------------*/
#define PRAGMA_BIND "achievement.wav"
#define PRAGMA_BIND "achievement1.wav"
#define PRAGMA_BIND "collect.wav"

/*-----------------------------*/
/* graphics\items */
/*-----------------------------*/
#define PRAGMA_BIND "angelhaken.tga"
#define PRAGMA_BIND "batterien.tga"
#define PRAGMA_BIND "brechstange.tga"
#define PRAGMA_BIND "fernbedienung.tga"
#define PRAGMA_BIND "futter.tga"
#define PRAGMA_BIND "gaffertape.tga"
#define PRAGMA_BIND "muenzen.tga"
#define PRAGMA_BIND "portemonaie.tga"
#define PRAGMA_BIND "revolver.tga"
#define PRAGMA_BIND "schluessel.tga"
#define PRAGMA_BIND "taschenlampe.tga"
#define PRAGMA_BIND "thermoskanne.tga"
#define PRAGMA_BIND "visitenkarte.tga"
#define PRAGMA_BIND "wd40.tga"
#define PRAGMA_BIND "zaubererstab.tga"
#define PRAGMA_BIND "zaubererstab_haken_tape.tga"
#define PRAGMA_BIND "zaubererstab_haken_wacklig.tga"
#define PRAGMA_BIND "zucker.tga"
#define PRAGMA_BIND "zuckerrohr.tga"

#endif