#ifndef BINDINGS_H
#define BINDINGS_H

/* This file is auto generated. DO NOT MODIFY MANUALLY! */

/*-----------------------------*/
/* sounds\dialog01_jcl */
/*-----------------------------*/
#define PRAGMA_BIND "dlg01_jcl_01.ogg"
#define PRAGMA_BIND "dlg01_jcl_03.ogg"
#define PRAGMA_BIND "dlg01_jcl_05b.ogg"
#define PRAGMA_BIND "dlg01_jcl_06.ogg"
#define PRAGMA_BIND "dlg01_jcl_08.ogg"
#define PRAGMA_BIND "dlg01_jcl_10a.ogg"
#define PRAGMA_BIND "dlg01_jcl_10b.ogg"
#define PRAGMA_BIND "dlg01_jcl_10c.ogg"
#define PRAGMA_BIND "dlg01_jcl_11.ogg"
#define PRAGMA_BIND "dlg01_jcl_13.ogg"
#define PRAGMA_BIND "dlg01_jcl_15.ogg"
#define PRAGMA_BIND "dlg01_jcl_17.ogg"
#define PRAGMA_BIND "dlg01_jcl_19.ogg"
#define PRAGMA_BIND "dlg01_jcl_21.ogg"
#define PRAGMA_BIND "dlg01_jcl_23.ogg"
#define PRAGMA_BIND "dlg01_jcl_25.ogg"
#define PRAGMA_BIND "dlg01_jcl_27.ogg"
#define PRAGMA_BIND "dlg01_jcl_29.ogg"
#define PRAGMA_BIND "dlg01_jcl_31.ogg"
#define PRAGMA_BIND "dlg01_jcl_33.ogg"
#define PRAGMA_BIND "dlg01_jcl_35.ogg"
#define PRAGMA_BIND "dlg01_jcl_37.ogg"
#define PRAGMA_BIND "dlg01_jcl_39.ogg"
#define PRAGMA_BIND "dlg01_morbius_00.ogg"
#define PRAGMA_BIND "dlg01_morbius_02.ogg"
#define PRAGMA_BIND "dlg01_morbius_04a.ogg"
#define PRAGMA_BIND "dlg01_morbius_04b.ogg"
#define PRAGMA_BIND "dlg01_morbius_07.ogg"
#define PRAGMA_BIND "dlg01_morbius_09a.ogg"
#define PRAGMA_BIND "dlg01_morbius_09b.ogg"
#define PRAGMA_BIND "dlg01_morbius_09c.ogg"
#define PRAGMA_BIND "dlg01_morbius_12.ogg"
#define PRAGMA_BIND "dlg01_morbius_14.ogg"
#define PRAGMA_BIND "dlg01_morbius_16.ogg"
#define PRAGMA_BIND "dlg01_morbius_18.ogg"
#define PRAGMA_BIND "dlg01_morbius_20.ogg"
#define PRAGMA_BIND "dlg01_morbius_22.ogg"
#define PRAGMA_BIND "dlg01_morbius_24.ogg"
#define PRAGMA_BIND "dlg01_morbius_26.ogg"
#define PRAGMA_BIND "dlg01_morbius_28.ogg"
#define PRAGMA_BIND "dlg01_morbius_30.ogg"
#define PRAGMA_BIND "dlg01_morbius_32.ogg"
#define PRAGMA_BIND "dlg01_morbius_34.ogg"
#define PRAGMA_BIND "dlg01_morbius_36.ogg"
#define PRAGMA_BIND "dlg01_morbius_38.ogg"

/*-----------------------------*/
/* sounds\dialog02_fritz */
/*-----------------------------*/
#define PRAGMA_BIND "dlg02_fritz_00.ogg"
#define PRAGMA_BIND "dlg02_fritz_03.ogg"
#define PRAGMA_BIND "dlg02_fritz_05a.ogg"
#define PRAGMA_BIND "dlg02_fritz_05b.ogg"
#define PRAGMA_BIND "dlg02_fritz_06.ogg"
#define PRAGMA_BIND "dlg02_fritz_08.ogg"
#define PRAGMA_BIND "dlg02_fritz_10.ogg"
#define PRAGMA_BIND "dlg02_fritz_12.ogg"
#define PRAGMA_BIND "dlg02_fritz_14.ogg"
#define PRAGMA_BIND "dlg02_fritz_16.ogg"
#define PRAGMA_BIND "dlg02_fritz_18.ogg"
#define PRAGMA_BIND "dlg02_fritz_20.ogg"
#define PRAGMA_BIND "dlg02_fritz_22.ogg"
#define PRAGMA_BIND "dlg02_morbius_01.ogg"
#define PRAGMA_BIND "dlg02_morbius_02.ogg"
#define PRAGMA_BIND "dlg02_morbius_04a.ogg"
#define PRAGMA_BIND "dlg02_morbius_04b.ogg"
#define PRAGMA_BIND "dlg02_morbius_07.ogg"
#define PRAGMA_BIND "dlg02_morbius_09.ogg"
#define PRAGMA_BIND "dlg02_morbius_11.ogg"
#define PRAGMA_BIND "dlg02_morbius_13.ogg"
#define PRAGMA_BIND "dlg02_morbius_15.ogg"
#define PRAGMA_BIND "dlg02_morbius_17.ogg"
#define PRAGMA_BIND "dlg02_morbius_19.ogg"
#define PRAGMA_BIND "dlg02_morbius_21.ogg"

/*-----------------------------*/
/* sounds\dialog03_galep */
/*-----------------------------*/
#define PRAGMA_BIND "dlg03_galep_00.ogg"
#define PRAGMA_BIND "dlg03_galep_02.ogg"
#define PRAGMA_BIND "dlg03_galep_04.ogg"
#define PRAGMA_BIND "dlg03_galep_06.ogg"
#define PRAGMA_BIND "dlg03_galep_08.ogg"
#define PRAGMA_BIND "dlg03_galep_10.ogg"
#define PRAGMA_BIND "dlg03_galep_12.ogg"
#define PRAGMA_BIND "dlg03_galep_14.ogg"
#define PRAGMA_BIND "dlg03_galep_16.ogg"
#define PRAGMA_BIND "dlg03_galep_18.ogg"
#define PRAGMA_BIND "dlg03_galep_20.ogg"
#define PRAGMA_BIND "dlg03_galep_22.ogg"
#define PRAGMA_BIND "dlg03_galep_24.ogg"
#define PRAGMA_BIND "dlg03_morbius_01.ogg"
#define PRAGMA_BIND "dlg03_morbius_03.ogg"
#define PRAGMA_BIND "dlg03_morbius_05.ogg"
#define PRAGMA_BIND "dlg03_morbius_07.ogg"
#define PRAGMA_BIND "dlg03_morbius_09.ogg"
#define PRAGMA_BIND "dlg03_morbius_11.ogg"
#define PRAGMA_BIND "dlg03_morbius_13.ogg"
#define PRAGMA_BIND "dlg03_morbius_15.ogg"
#define PRAGMA_BIND "dlg03_morbius_17.ogg"
#define PRAGMA_BIND "dlg03_morbius_19.ogg"
#define PRAGMA_BIND "dlg03_morbius_21.ogg"
#define PRAGMA_BIND "dlg03_morbius_23.ogg"

/*-----------------------------*/
/* sounds\dialog04_greek */
/*-----------------------------*/
#define PRAGMA_BIND "dlg04_greek_01.ogg"
#define PRAGMA_BIND "dlg04_greek_03.ogg"
#define PRAGMA_BIND "dlg04_greek_05.ogg"
#define PRAGMA_BIND "dlg04_greek_07.ogg"
#define PRAGMA_BIND "dlg04_greek_09.ogg"
#define PRAGMA_BIND "dlg04_greek_11.ogg"
#define PRAGMA_BIND "dlg04_greek_14.ogg"
#define PRAGMA_BIND "dlg04_greek_16.ogg"
#define PRAGMA_BIND "dlg04_greek_18.ogg"
#define PRAGMA_BIND "dlg04_greek_20.ogg"
#define PRAGMA_BIND "dlg04_greek_22.ogg"
#define PRAGMA_BIND "dlg04_greek_24.ogg"
#define PRAGMA_BIND "dlg04_greek_26.ogg"
#define PRAGMA_BIND "dlg04_greek_28.ogg"
#define PRAGMA_BIND "dlg04_greek_30.ogg"
#define PRAGMA_BIND "dlg04_greek_32.ogg"
#define PRAGMA_BIND "dlg04_greek_34.ogg"
#define PRAGMA_BIND "dlg04_morbius_00.ogg"
#define PRAGMA_BIND "dlg04_morbius_02.ogg"
#define PRAGMA_BIND "dlg04_morbius_04.ogg"
#define PRAGMA_BIND "dlg04_morbius_06.ogg"
#define PRAGMA_BIND "dlg04_morbius_08.ogg"
#define PRAGMA_BIND "dlg04_morbius_10.ogg"
#define PRAGMA_BIND "dlg04_morbius_12.ogg"
#define PRAGMA_BIND "dlg04_morbius_13.ogg"
#define PRAGMA_BIND "dlg04_morbius_15.ogg"
#define PRAGMA_BIND "dlg04_morbius_17.ogg"
#define PRAGMA_BIND "dlg04_morbius_19.ogg"
#define PRAGMA_BIND "dlg04_morbius_21.ogg"
#define PRAGMA_BIND "dlg04_morbius_23.ogg"
#define PRAGMA_BIND "dlg04_morbius_25.ogg"
#define PRAGMA_BIND "dlg04_morbius_27.ogg"
#define PRAGMA_BIND "dlg04_morbius_29.ogg"
#define PRAGMA_BIND "dlg04_morbius_31.ogg"
#define PRAGMA_BIND "dlg04_morbius_33.ogg"

/*-----------------------------*/
/* sounds\dialog05_cbabe */
/*-----------------------------*/
#define PRAGMA_BIND "dlg05_cbabe_01.ogg"
#define PRAGMA_BIND "dlg05_cbabe_03.ogg"
#define PRAGMA_BIND "dlg05_cbabe_05.ogg"
#define PRAGMA_BIND "dlg05_cbabe_07.ogg"
#define PRAGMA_BIND "dlg05_cbabe_09.ogg"
#define PRAGMA_BIND "dlg05_cbabe_11.ogg"
#define PRAGMA_BIND "dlg05_cbabe_13.ogg"
#define PRAGMA_BIND "dlg05_cbabe_15.ogg"
#define PRAGMA_BIND "dlg05_cbabe_17.ogg"

/*-----------------------------*/
/* sounds\items */
/*-----------------------------*/
#define PRAGMA_BIND "comb_batterien_taschenlampe.ogg"
#define PRAGMA_BIND "comb_brechstange_tuer.ogg"
#define PRAGMA_BIND "comb_futter_gecko.ogg"
#define PRAGMA_BIND "comb_schluessel_schublade.ogg"
#define PRAGMA_BIND "comb_wd40_tuer.ogg"
#define PRAGMA_BIND "itm_a401.ogg"
#define PRAGMA_BIND "itm_brechstange01.ogg"
#define PRAGMA_BIND "itm_dunkelkammer01.ogg"
#define PRAGMA_BIND "itm_fernbedienung01.ogg"
#define PRAGMA_BIND "itm_fernbedienung02.ogg"
#define PRAGMA_BIND "itm_gecko01.ogg"
#define PRAGMA_BIND "itm_gecko02.ogg"
#define PRAGMA_BIND "itm_guardmdl01.ogg"
#define PRAGMA_BIND "itm_guardmdl02.ogg"
#define PRAGMA_BIND "itm_guardmdl03.ogg"
#define PRAGMA_BIND "itm_guardmdl04.ogg"
#define PRAGMA_BIND "itm_guardmdl05.ogg"
#define PRAGMA_BIND "itm_guardmdl06.ogg"
#define PRAGMA_BIND "itm_guardmdl07.ogg"
#define PRAGMA_BIND "itm_laptop01.ogg"
#define PRAGMA_BIND "itm_regal01.ogg"
#define PRAGMA_BIND "itm_reptilfutter01.ogg"
#define PRAGMA_BIND "itm_revolver01.ogg"
#define PRAGMA_BIND "itm_revolver02.ogg"
#define PRAGMA_BIND "itm_rosatelefon01.ogg"
#define PRAGMA_BIND "itm_schluessel01.ogg"
#define PRAGMA_BIND "itm_schluessel_unzugaenglich01.ogg"
#define PRAGMA_BIND "itm_schluessel_unzugaenglich02.ogg"
#define PRAGMA_BIND "itm_schluessel_unzugaenglich03.ogg"
#define PRAGMA_BIND "itm_schublade_zu01.ogg"
#define PRAGMA_BIND "itm_schublade_zu02.ogg"
#define PRAGMA_BIND "itm_schublade_zu03.ogg"
#define PRAGMA_BIND "itm_schublade_zu04.ogg"
#define PRAGMA_BIND "itm_taschenlampe01.ogg"
#define PRAGMA_BIND "itm_taschenlampe02.ogg"
#define PRAGMA_BIND "itm_taschenlampe03.ogg"
#define PRAGMA_BIND "itm_telefonzelle01.ogg"
#define PRAGMA_BIND "itm_verrostetuer01.ogg"
#define PRAGMA_BIND "itm_verrostetuer02.ogg"
#define PRAGMA_BIND "itm_visitenkarte01.ogg"
#define PRAGMA_BIND "itm_wd4001.ogg"

/*-----------------------------*/
/* sounds\items */
/*-----------------------------*/
#define PRAGMA_BIND "achievement1.wav"

/*-----------------------------*/
/* sounds\monolog */
/*-----------------------------*/
#define PRAGMA_BIND "mlg00_morbius_01.ogg"
#define PRAGMA_BIND "mlg01_morbius.ogg"
#define PRAGMA_BIND "mlg02_morbius.ogg"
#define PRAGMA_BIND "scene01_end_fail.ogg"
#define PRAGMA_BIND "scene01_end_prompt01.ogg"
#define PRAGMA_BIND "scene01_end_prompt02.ogg"
#define PRAGMA_BIND "scene01_end_proper.ogg"

/*-----------------------------*/
/* graphics\items */
/*-----------------------------*/
#define PRAGMA_BIND "batteries.png"
#define PRAGMA_BIND "business_card.png"
#define PRAGMA_BIND "coffee_can.png"
#define PRAGMA_BIND "coins.png"
#define PRAGMA_BIND "crowbar.png"
#define PRAGMA_BIND "flashlight.png"
#define PRAGMA_BIND "flashlight_on.png"
#define PRAGMA_BIND "gaffer.png"
#define PRAGMA_BIND "gecko_food.png"
#define PRAGMA_BIND "hook.png"
#define PRAGMA_BIND "key.png"
#define PRAGMA_BIND "revolver.png"
#define PRAGMA_BIND "staff.png"
#define PRAGMA_BIND "staff_hook.png"
#define PRAGMA_BIND "staff_hook_gaffer.png"
#define PRAGMA_BIND "sugar_cane.png"
#define PRAGMA_BIND "sugar_pot.png"
#define PRAGMA_BIND "tv_remote.png"
#define PRAGMA_BIND "wallet.png"
#define PRAGMA_BIND "wd40.png"

/*-----------------------------*/
/* models\items */
/*-----------------------------*/
#define PRAGMA_BIND "business_card.tga"
#define PRAGMA_BIND "coffee_can.tga"
#define PRAGMA_BIND "gecko_yum.tga"

/*-----------------------------*/
/* models\items */
/*-----------------------------*/
#define PRAGMA_BIND "a3_box.mdl"
#define PRAGMA_BIND "business_card.mdl"
#define PRAGMA_BIND "coffee_can.mdl"
#define PRAGMA_BIND "crowbar.mdl"
#define PRAGMA_BIND "downtown.mdl"
#define PRAGMA_BIND "fernbedienung.mdl"
#define PRAGMA_BIND "flashlight.mdl"
#define PRAGMA_BIND "gecko_food.mdl"
#define PRAGMA_BIND "meisterdesfeuers.mdl"
#define PRAGMA_BIND "revolver.mdl"
#define PRAGMA_BIND "schluessel.mdl"
#define PRAGMA_BIND "schublade_geschlossen.mdl"
#define PRAGMA_BIND "schublade_offen.mdl"
#define PRAGMA_BIND "topf.mdl"
#define PRAGMA_BIND "wd40.mdl"

/*-----------------------------*/
/* shaders */
/*-----------------------------*/
#define PRAGMA_BIND "animTree.fxo"
#define PRAGMA_BIND "bump.fxo"
#define PRAGMA_BIND "character.fxo"
#define PRAGMA_BIND "chrome.fxo"
#define PRAGMA_BIND "chromebump.fxo"
#define PRAGMA_BIND "cloud.fxo"
#define PRAGMA_BIND "envBump.fxo"
#define PRAGMA_BIND "envglass.fxo"
#define PRAGMA_BIND "envglassbump.fxo"
#define PRAGMA_BIND "envMap.fxo"
#define PRAGMA_BIND "envwater.fxo"
#define PRAGMA_BIND "floorMirror.fxo"
#define PRAGMA_BIND "item.fxo"
#define PRAGMA_BIND "level_change_t.fxo"
#define PRAGMA_BIND "lightCount.fxo"
#define PRAGMA_BIND "mirrorFloor.fxo"
#define PRAGMA_BIND "mirrorWater.fxo"
#define PRAGMA_BIND "parallax.fxo"
#define PRAGMA_BIND "pom.fxo"
#define PRAGMA_BIND "pp_bias.fxo"
#define PRAGMA_BIND "pp_bleach.fxo"
#define PRAGMA_BIND "pp_blur.fxo"
#define PRAGMA_BIND "pp_colorshift.fxo"
#define PRAGMA_BIND "pp_colorspin.fxo"
#define PRAGMA_BIND "pp_desaturate.fxo"
#define PRAGMA_BIND "pp_dilate.fxo"
#define PRAGMA_BIND "pp_displace.fxo"
#define PRAGMA_BIND "pp_emboss.fxo"
#define PRAGMA_BIND "pp_erode.fxo"
#define PRAGMA_BIND "pp_gamma.fxo"
#define PRAGMA_BIND "pp_gaussian.fxo"
#define PRAGMA_BIND "pp_hdr.fxo"
#define PRAGMA_BIND "pp_kuwahara.fxo"
#define PRAGMA_BIND "pp_laplace.fxo"
#define PRAGMA_BIND "pp_lens.fxo"
#define PRAGMA_BIND "pp_median.fxo"
#define PRAGMA_BIND "pp_monochrome.fxo"
#define PRAGMA_BIND "pp_negative.fxo"
#define PRAGMA_BIND "pp_posterize.fxo"
#define PRAGMA_BIND "pp_sepia.fxo"
#define PRAGMA_BIND "pp_sharpen.fxo"
#define PRAGMA_BIND "pp_sharpen2.fxo"
#define PRAGMA_BIND "pp_sobel.fxo"
#define PRAGMA_BIND "specBump.fxo"
#define PRAGMA_BIND "specParallax.fxo"
#define PRAGMA_BIND "specPom.fxo"
#define PRAGMA_BIND "terraintex.fxo"
#define PRAGMA_BIND "terraintex3.fxo"
#define PRAGMA_BIND "toon.fxo"
#define PRAGMA_BIND "turbulence.fxo"
#define PRAGMA_BIND "waterEnv.fxo"
#define PRAGMA_BIND "waterMirror.fxo"

#endif